[package]
name = "Dao_Zk_Proof_Contract_Applying_Curve25519"
version = "0.1.0"
edition = "2021"

[dependencies]
curve25519-dalek = "4.1.3"
merlin = "3.0.0"
rand = "0.8.5"
sha3 = "0.10.8"
solana-program = "2.0.2"
subtle = "2.6.1"
