[package]
name = "generate_zk_proof"
version = "0.1.0"
edition = "2021"

[dependencies]
bellman = "0.14.0"
bls12_381 = "0.8.0"
num-bigint = "0.4.6"
num-traits = "0.2.19"
pairing = "0.23.0"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
sha2 = "0.10.8"
