[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dao_voting = "2ZKcfLiwNShCekPnsgq1hQSmGF1fU6iT4Q3rrMXet4p2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ritikbhatt020/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
